In [1]:
import pandas as pd

datanew1=pd.read_csv("newtest3.csv")

datanew1

    S.N.               Name   Contact No.  Year          Address  Price Winner
0    1.0     Mohit Tripathi  8.887331e+09   2nd        Prayagraj           NaN
1    2.0        Jay Narayan  9.511494e+09   3rd        Sultanpur        3000.0
2    3.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
3    4.0                NaN           NaN   NaN              NaN           NaN
4    5.0       Sonush Kumar  8.400716e+09   2nd       Shajahapur        6000.0
5    6.0        Vivek Kumar  9.151481e+09   3rd        Sonbhadra        7000.0
6    7.0      Pranshu Dubey  8.707037e+09   2nd         Mirzapur           NaN
7    8.0                NaN  8.273730e+09   3rd         Bareilly           NaN
8    9.0                NaN  9.565256e+09   2nd           Ballia        3000.0
9   10.0                NaN  7.310363e+09   NaN           Ballia        4000.0
10  11.0                NaN           NaN   2nd   Ambedkar Nagar        5000.0
11  12.0                NaN           NaN   2nd         Bareilly           NaN
12  13.0                NaN           NaN   NaN      RaeBareilly           NaN
13  14.0       Shivam Kumar           NaN   3rd            Patna        2000.0
14  15.0  Kishan Raghuvansh           NaN   2nd  Khitaura Badaun        3000.0
15  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
16   NaN                NaN           NaN   NaN              NaN           NaN
17  18.0              Arpit  8.853029e+09   2nd          Jaunpur           NaN
18  19.0        Laki Sharma  8.267968e+09   2nd      TiliyaKhata           NaN
19  20.0     Utkarsh Sharma  7.317762e+09   2nd      Shajahanpur           NaN
20  21.0                NaN  7.398558e+09   NaN              Mau           NaN
21  22.0                NaN  8.115515e+09  4rth           Ballia           NaN
22  23.0                NaN  8.115192e+09   2nd              Mau        2000.0
23  24.0            Shivraj  8.409108e+09   2nd              Mau        3000.0
24  25.0      Karan Bhrdwaj  9.795591e+09  4rth       Farukhabad        4000.0
25  26.0        Anuj Gautam  8.601098e+09   2nd           Kanpur        5000.0
26  27.0        Ankit Kumar  7.817895e+09  4rth         Bareilly        6000.0
27  28.0        Arjun Singh  9.389454e+09   2nd         Bareilly        7000.0
28  29.0   Prince Prajapati  7.800170e+09   3rd        Gorakhpur        8000.0

In [12]:
import pandas as pd

datanew1=pd.read_csv("newtest3.csv")
# datanew1.dropna()

# datanew1.dropna(axis=1)
datanew1.dropna(axis=0)

    S.N.              Name   Contact No.  Year     Address  Price Winner
1    2.0       Jay Narayan  9.511494e+09   3rd   Sultanpur        3000.0
2    3.0          Aman Pal  9.151503e+09   2nd     Jaunpur        4000.0
4    5.0      Sonush Kumar  8.400716e+09   2nd  Shajahapur        6000.0
5    6.0       Vivek Kumar  9.151481e+09   3rd   Sonbhadra        7000.0
15  16.0      Aditya Kumar  7.645071e+09   2nd  Gaya Bihar        4000.0
23  24.0           Shivraj  8.409108e+09   2nd         Mau        3000.0
24  25.0     Karan Bhrdwaj  9.795591e+09  4rth  Farukhabad        4000.0
25  26.0       Anuj Gautam  8.601098e+09   2nd      Kanpur        5000.0
26  27.0       Ankit Kumar  7.817895e+09  4rth    Bareilly        6000.0
27  28.0       Arjun Singh  9.389454e+09   2nd    Bareilly        7000.0
28  29.0  Prince Prajapati  7.800170e+09   3rd   Gorakhpur        8000.0

In [ ]:
# datanew1.dropna(how="any")
# datanew1.dropna(how="all",axis=0)

    S.N.              Name   Contact No.  Year     Address  Price Winner
1    2.0       Jay Narayan  9.511494e+09   3rd   Sultanpur        3000.0
2    3.0          Aman Pal  9.151503e+09   2nd     Jaunpur        4000.0
4    5.0      Sonush Kumar  8.400716e+09   2nd  Shajahapur        6000.0
5    6.0       Vivek Kumar  9.151481e+09   3rd   Sonbhadra        7000.0
15  16.0      Aditya Kumar  7.645071e+09   2nd  Gaya Bihar        4000.0
23  24.0           Shivraj  8.409108e+09   2nd         Mau        3000.0
24  25.0     Karan Bhrdwaj  9.795591e+09  4rth  Farukhabad        4000.0
25  26.0       Anuj Gautam  8.601098e+09   2nd      Kanpur        5000.0
26  27.0       Ankit Kumar  7.817895e+09  4rth    Bareilly        6000.0
27  28.0       Arjun Singh  9.389454e+09   2nd    Bareilly        7000.0
28  29.0  Prince Prajapati  7.800170e+09   3rd   Gorakhpur        8000.0

In [15]:
# datanew1.dropna(subset=["Name"])
datanew1.dropna(subset=["Name","Year"])

    S.N.               Name   Contact No.  Year          Address  Price Winner
0    1.0     Mohit Tripathi  8.887331e+09   2nd        Prayagraj           NaN
1    2.0        Jay Narayan  9.511494e+09   3rd        Sultanpur        3000.0
2    3.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
4    5.0       Sonush Kumar  8.400716e+09   2nd       Shajahapur        6000.0
5    6.0        Vivek Kumar  9.151481e+09   3rd        Sonbhadra        7000.0
6    7.0      Pranshu Dubey  8.707037e+09   2nd         Mirzapur           NaN
13  14.0       Shivam Kumar           NaN   3rd            Patna        2000.0
14  15.0  Kishan Raghuvansh           NaN   2nd  Khitaura Badaun        3000.0
15  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
17  18.0              Arpit  8.853029e+09   2nd          Jaunpur           NaN
18  19.0        Laki Sharma  8.267968e+09   2nd      TiliyaKhata           NaN
19  20.0     Utkarsh Sharma  7.317762e+09   2nd      Shajahanpur           NaN
23  24.0            Shivraj  8.409108e+09   2nd              Mau        3000.0
24  25.0      Karan Bhrdwaj  9.795591e+09  4rth       Farukhabad        4000.0
25  26.0        Anuj Gautam  8.601098e+09   2nd           Kanpur        5000.0
26  27.0        Ankit Kumar  7.817895e+09  4rth         Bareilly        6000.0
27  28.0        Arjun Singh  9.389454e+09   2nd         Bareilly        7000.0
28  29.0   Prince Prajapati  7.800170e+09   3rd        Gorakhpur        8000.0

In [17]:
import pandas as pd
datanew1=pd.read_csv("newtest3.csv")
# datanew1.dropna(thresh=5)

datanew1.dropna(thresh=3)
# datanew1

    S.N.               Name   Contact No.  Year          Address  Price Winner
0    1.0     Mohit Tripathi  8.887331e+09   2nd        Prayagraj           NaN
1    2.0        Jay Narayan  9.511494e+09   3rd        Sultanpur        3000.0
2    3.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
4    5.0       Sonush Kumar  8.400716e+09   2nd       Shajahapur        6000.0
5    6.0        Vivek Kumar  9.151481e+09   3rd        Sonbhadra        7000.0
6    7.0      Pranshu Dubey  8.707037e+09   2nd         Mirzapur           NaN
7    8.0                NaN  8.273730e+09   3rd         Bareilly           NaN
8    9.0                NaN  9.565256e+09   2nd           Ballia        3000.0
9   10.0                NaN  7.310363e+09   NaN           Ballia        4000.0
10  11.0                NaN           NaN   2nd   Ambedkar Nagar        5000.0
11  12.0                NaN           NaN   2nd         Bareilly           NaN
13  14.0       Shivam Kumar           NaN   3rd            Patna        2000.0
14  15.0  Kishan Raghuvansh           NaN   2nd  Khitaura Badaun        3000.0
15  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
17  18.0              Arpit  8.853029e+09   2nd          Jaunpur           NaN
18  19.0        Laki Sharma  8.267968e+09   2nd      TiliyaKhata           NaN
19  20.0     Utkarsh Sharma  7.317762e+09   2nd      Shajahanpur           NaN
20  21.0                NaN  7.398558e+09   NaN              Mau           NaN
21  22.0                NaN  8.115515e+09  4rth           Ballia           NaN
22  23.0                NaN  8.115192e+09   2nd              Mau        2000.0
23  24.0            Shivraj  8.409108e+09   2nd              Mau        3000.0
24  25.0      Karan Bhrdwaj  9.795591e+09  4rth       Farukhabad        4000.0
25  26.0        Anuj Gautam  8.601098e+09   2nd           Kanpur        5000.0
26  27.0        Ankit Kumar  7.817895e+09  4rth         Bareilly        6000.0
27  28.0        Arjun Singh  9.389454e+09   2nd         Bareilly        7000.0
28  29.0   Prince Prajapati  7.800170e+09   3rd        Gorakhpur        8000.0

In [26]:
# datanew1.fillna("python")

# datanew1.fillna({"Price Winner":"2000"})

# datanew1.fillna({"Price Winner":"2000","Name":"Rohan Pal"})

datanew1

# datanew1.fillna(method="bfill")
datanew1.fillna(method="ffill",axis=0)

C:\Users\pc\AppData\Local\Temp\ipykernel_2732\2086327275.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  datanew1.fillna(method="ffill",axis=0)

    S.N.               Name   Contact No.  Year          Address  Price Winner
0    1.0     Mohit Tripathi  8.887331e+09   2nd        Prayagraj           NaN
1    2.0        Jay Narayan  9.511494e+09   3rd        Sultanpur        3000.0
2    3.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
3    4.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
4    5.0       Sonush Kumar  8.400716e+09   2nd       Shajahapur        6000.0
5    6.0        Vivek Kumar  9.151481e+09   3rd        Sonbhadra        7000.0
6    7.0      Pranshu Dubey  8.707037e+09   2nd         Mirzapur        7000.0
7    8.0      Pranshu Dubey  8.273730e+09   3rd         Bareilly        7000.0
8    9.0      Pranshu Dubey  9.565256e+09   2nd           Ballia        3000.0
9   10.0      Pranshu Dubey  7.310363e+09   2nd           Ballia        4000.0
10  11.0      Pranshu Dubey  7.310363e+09   2nd   Ambedkar Nagar        5000.0
11  12.0      Pranshu Dubey  7.310363e+09   2nd         Bareilly        5000.0
12  13.0      Pranshu Dubey  7.310363e+09   2nd      RaeBareilly        5000.0
13  14.0       Shivam Kumar  7.310363e+09   3rd            Patna        2000.0
14  15.0  Kishan Raghuvansh  7.310363e+09   2nd  Khitaura Badaun        3000.0
15  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
16  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
17  18.0              Arpit  8.853029e+09   2nd          Jaunpur        4000.0
18  19.0        Laki Sharma  8.267968e+09   2nd      TiliyaKhata        4000.0
19  20.0     Utkarsh Sharma  7.317762e+09   2nd      Shajahanpur        4000.0
20  21.0     Utkarsh Sharma  7.398558e+09   2nd              Mau        4000.0
21  22.0     Utkarsh Sharma  8.115515e+09  4rth           Ballia        4000.0
22  23.0     Utkarsh Sharma  8.115192e+09   2nd              Mau        2000.0
23  24.0            Shivraj  8.409108e+09   2nd              Mau        3000.0
24  25.0      Karan Bhrdwaj  9.795591e+09  4rth       Farukhabad        4000.0
25  26.0        Anuj Gautam  8.601098e+09   2nd           Kanpur        5000.0
26  27.0        Ankit Kumar  7.817895e+09  4rth         Bareilly        6000.0
27  28.0        Arjun Singh  9.389454e+09   2nd         Bareilly        7000.0
28  29.0   Prince Prajapati  7.800170e+09   3rd        Gorakhpur        8000.0

In [ ]:
# datanew1.fillna({"Price Winner":datanew1["Price Winner"].mean()})
# datanew1.fillna({"Price Winner":datanew1["Price Winner"].mode()[0]})
# datanew1.fillna({"Price Winner":datanew1["Price Winner"].median()})

    S.N.               Name   Contact No.  Year          Address  Price Winner
0    1.0     Mohit Tripathi  8.887331e+09   2nd        Prayagraj        4000.0
1    2.0        Jay Narayan  9.511494e+09   3rd        Sultanpur        3000.0
2    3.0           Aman Pal  9.151503e+09   2nd          Jaunpur        4000.0
3    4.0                NaN           NaN   NaN              NaN        4000.0
4    5.0       Sonush Kumar  8.400716e+09   2nd       Shajahapur        6000.0
5    6.0        Vivek Kumar  9.151481e+09   3rd        Sonbhadra        7000.0
6    7.0      Pranshu Dubey  8.707037e+09   2nd         Mirzapur        4000.0
7    8.0                NaN  8.273730e+09   3rd         Bareilly        4000.0
8    9.0                NaN  9.565256e+09   2nd           Ballia        3000.0
9   10.0                NaN  7.310363e+09   NaN           Ballia        4000.0
10  11.0                NaN           NaN   2nd   Ambedkar Nagar        5000.0
11  12.0                NaN           NaN   2nd         Bareilly        4000.0
12  13.0                NaN           NaN   NaN      RaeBareilly        4000.0
13  14.0       Shivam Kumar           NaN   3rd            Patna        2000.0
14  15.0  Kishan Raghuvansh           NaN   2nd  Khitaura Badaun        3000.0
15  16.0       Aditya Kumar  7.645071e+09   2nd       Gaya Bihar        4000.0
16   NaN                NaN           NaN   NaN              NaN        4000.0
17  18.0              Arpit  8.853029e+09   2nd          Jaunpur        4000.0
18  19.0        Laki Sharma  8.267968e+09   2nd      TiliyaKhata        4000.0
19  20.0     Utkarsh Sharma  7.317762e+09   2nd      Shajahanpur        4000.0
20  21.0                NaN  7.398558e+09   NaN              Mau        4000.0
21  22.0                NaN  8.115515e+09  4rth           Ballia        4000.0
22  23.0                NaN  8.115192e+09   2nd              Mau        2000.0
23  24.0            Shivraj  8.409108e+09   2nd              Mau        3000.0
24  25.0      Karan Bhrdwaj  9.795591e+09  4rth       Farukhabad        4000.0
25  26.0        Anuj Gautam  8.601098e+09   2nd           Kanpur        5000.0
26  27.0        Ankit Kumar  7.817895e+09  4rth         Bareilly        6000.0
27  28.0        Arjun Singh  9.389454e+09   2nd         Bareilly        7000.0
28  29.0   Prince Prajapati  7.800170e+09   3rd        Gorakhpur        8000.0

In [30]:
datanew1.fillna("Python",limit=4)

,S.N.,Name,Contact No.,Year,Address,Price Winner
0,1.0,Mohit Tripathi,8887331179.0,2nd,Prayagraj,Python
1,2.0,Jay Narayan,9511493970.0,3rd,Sultanpur,3000.0
2,3.0,Aman Pal,9151503447.0,2nd,Jaunpur,4000.0
3,4.0,Python,Python,Python,Python,Python
4,5.0,Sonush Kumar,8400716124.0,2nd,Shajahapur,6000.0
5,6.0,Vivek Kumar,9151480914.0,3rd,Sonbhadra,7000.0
6,7.0,Pranshu Dubey,8707037056.0,2nd,Mirzapur,Python
7,8.0,Python,8273730104.0,3rd,Bareilly,Python
8,9.0,Python,9565256344.0,2nd,Ballia,3000.0
9,10.0,Python,7310362981.0,Python,Ballia,4000.0
10,11.0,NaN,Python,2nd,Ambedkar Nagar,5000.0
11,12.0,NaN,Python,2nd,Bareilly,NaN
12,13.0,NaN,Python,Python,RaeBareilly,NaN
13,14.0,Shivam Kumar,NaN,3rd,Patna,2000.0
14,15.0,Kishan Raghuvansh,NaN,2nd,Khitaura Badaun,3000.0
15,16.0,Aditya Kumar,7645071129.0,2nd,Gaya Bihar,4000.0
16,Python,NaN,NaN,Python,Python,NaN
17,18.0,Arpit,8853029377.0,2nd,Jaunpur,NaN
18,19.0,Laki Sharma,8267968235.0,2nd,TiliyaKhata,NaN
19,20.0,Utkarsh Sharma,7317762256.0,2nd,Shajahanpur,NaN
20,21.0,NaN,7398558431.0,NaN,Mau,NaN
21,22.0,NaN,8115514548.0,4rth,Ballia,NaN
22,23.0,NaN,8115191992.0,2nd,Mau,2000.0
23,24.0,Shivraj,8409108148.0,2nd,Mau,3000.0
24,25.0,Karan Bhrdwaj,9795590870.0,4rth,Farukhabad,4000.0
25,26.0,Anuj Gautam,8601097943.0,2nd,Kanpur,5000.0
26,27.0,Ankit Kumar,7817895076.0,4rth,Bareilly,6000.0
27,28.0,Arjun Singh,9389454010.0,2nd,Bareilly,7000.0
28,29.0,Prince Prajapati,7800170358.0,3rd,Gorakhpur,8000.0