# Handling CSV Data

In [18]:
import pandas as pd
set1={"a":[3,5,6,8],"s":[2,5,9,6],"d":[1,5,8,0]}

data1=pd.DataFrame(set1)
# data1

# data1.to_csv("myfile.csv")

# data1.to_csv("myfile2.csv",index=False)
data1.to_csv("hero.csv",index=False,header=["Hindi","Maths","Physics"])
data1

   a  s  d
0  3  2  1
1  5  5  5
2  6  9  8
3  8  6  0

### Read CSV File

In [19]:
r1=pd.read_csv("csv1.csv")
r1

,JE Code,Store,Country,Date,Item,List Price
0,I-1001,Moscow,Russia,10/6/2018,Microwave,80
1,I-1002,Toronto,Canada,4/23/2015,Microwave,80
2,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
3,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
4,I-1005,Sydney,Australia,3/3/2015,Toaster,50
5,I-1006,Shenzhen,China,4/25/2016,Iron,30
6,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
7,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
8,I-1009,London,UK,12/11/2015,Washing Machine,800
9,I-1010,Lima,Peru,9/7/2014,Iron,30
10,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
11,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
13,I-1014,Delhi,India,5/30/2014,Oven,500
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [20]:
import pandas as pd
r1=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",nrows=6)
r1

  JE Code      Store    Country       Date             Item  List Price
0  I-1001     Moscow     Russia  10/6/2018        Microwave          80
1  I-1002    Toronto     Canada  4/23/2015        Microwave          80
2  I-1003  Sao Paolo     Brazil   4/3/2017  Air conditioner         700
3  I-1004   Istanbul     Turkey  8/14/2018      Ceiling fan         150
4  I-1005     Sydney  Australia   3/3/2015          Toaster          50
5  I-1006   Shenzhen      China  4/25/2016             Iron          30

In [21]:
r1=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",nrows=3,usecols=["Store","Date","Country"])
# r1=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",usecols=["Store","Date","Country"])
r1

       Store Country       Date
0     Moscow  Russia  10/6/2018
1    Toronto  Canada  4/23/2015
2  Sao Paolo  Brazil   4/3/2017

In [22]:
import pandas as pd
r2=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",skiprows=5)
r2

    I-1005            Sydney     Australia    3/3/2015          Toaster    50
0   I-1006          Shenzhen         China   4/25/2016             Iron    30
1   I-1007              Lima          Peru    6/6/2016       Dishwasher   500
2   I-1008           Tijuana        Mexico    6/7/2016             Iron    30
3   I-1009            London            UK  12/11/2015  Washing Machine   800
4   I-1010              Lima          Peru    9/7/2014             Iron    30
5   I-1011            Riyadh  Saudi Arabia   10/7/2017     Refrigerator  1000
6   I-1012           Bangkok      Thailand   8/21/2014  Air conditioner   700
7   I-1013           Tijuana        Mexico    3/9/2015             Iron    30
8   I-1014             Delhi         India   5/30/2014             Oven   500
9   I-1015            Sydney     Australia  11/12/2018  Washing Machine   800
10  I-1016  Ho Chi Minh City       Vietnam   5/24/2015        Microwave    80
11  I-1017          Tel Aviv        Israel   12/6/2014     Refrigerator  1000

In [23]:
r2=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",index_col=["JE Code"])
r2

,Store,Country,Date,Item,List Price
JE Code,,,,,
I-1001,Moscow,Russia,10/6/2018,Microwave,80
I-1002,Toronto,Canada,4/23/2015,Microwave,80
I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
I-1005,Sydney,Australia,3/3/2015,Toaster,50
I-1006,Shenzhen,China,4/25/2016,Iron,30
I-1007,Lima,Peru,6/6/2016,Dishwasher,500
I-1008,Tijuana,Mexico,6/7/2016,Iron,30
I-1009,London,UK,12/11/2015,Washing Machine,800
I-1010,Lima,Peru,9/7/2014,Iron,30
I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
I-1013,Tijuana,Mexico,3/9/2015,Iron,30
I-1014,Delhi,India,5/30/2014,Oven,500
I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [24]:
r2=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",header=3)
r2

    I-1003         Sao Paolo        Brazil    4/3/2017  Air conditioner   700
0   I-1004          Istanbul        Turkey   8/14/2018      Ceiling fan   150
1   I-1005            Sydney     Australia    3/3/2015          Toaster    50
2   I-1006          Shenzhen         China   4/25/2016             Iron    30
3   I-1007              Lima          Peru    6/6/2016       Dishwasher   500
4   I-1008           Tijuana        Mexico    6/7/2016             Iron    30
5   I-1009            London            UK  12/11/2015  Washing Machine   800
6   I-1010              Lima          Peru    9/7/2014             Iron    30
7   I-1011            Riyadh  Saudi Arabia   10/7/2017     Refrigerator  1000
8   I-1012           Bangkok      Thailand   8/21/2014  Air conditioner   700
9   I-1013           Tijuana        Mexico    3/9/2015             Iron    30
10  I-1014             Delhi         India   5/30/2014             Oven   500
11  I-1015            Sydney     Australia  11/12/2018  Washing Machine   800
12  I-1016  Ho Chi Minh City       Vietnam   5/24/2015        Microwave    80
13  I-1017          Tel Aviv        Israel   12/6/2014     Refrigerator  1000

In [27]:
r2=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",names=["A1","B1","C1","D1","E1","F1"])
r2

,A1,B1,C1,D1,E1,F1
0,JE Code,Store,Country,Date,Item,List Price
1,I-1001,Moscow,Russia,10/6/2018,Microwave,80
2,I-1002,Toronto,Canada,4/23/2015,Microwave,80
3,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
4,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
5,I-1005,Sydney,Australia,3/3/2015,Toaster,50
6,I-1006,Shenzhen,China,4/25/2016,Iron,30
7,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
8,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
9,I-1009,London,UK,12/11/2015,Washing Machine,800
10,I-1010,Lima,Peru,9/7/2014,Iron,30
11,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
12,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
13,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
14,I-1014,Delhi,India,5/30/2014,Oven,500
15,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
16,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
17,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [28]:
# r3=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",header=None)
import pandas as pd
r3=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",header=None)
r3

,0,1,2,3,4,5
0,JE Code,Store,Country,Date,Item,List Price
1,I-1001,Moscow,Russia,10/6/2018,Microwave,80
2,I-1002,Toronto,Canada,4/23/2015,Microwave,80
3,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
4,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
5,I-1005,Sydney,Australia,3/3/2015,Toaster,50
6,I-1006,Shenzhen,China,4/25/2016,Iron,30
7,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
8,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
9,I-1009,London,UK,12/11/2015,Washing Machine,800
10,I-1010,Lima,Peru,9/7/2014,Iron,30
11,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
12,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
13,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
14,I-1014,Delhi,India,5/30/2014,Oven,500
15,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
16,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
17,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [29]:
r3=pd.read_csv("C:\\Users\\pc\\Desktop\\Data_Science\\Pandas\\csv1.csv",dtype={"List Price":"float"})
r3

,JE Code,Store,Country,Date,Item,List Price
0,I-1001,Moscow,Russia,10/6/2018,Microwave,80.0
1,I-1002,Toronto,Canada,4/23/2015,Microwave,80.0
2,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700.0
3,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150.0
4,I-1005,Sydney,Australia,3/3/2015,Toaster,50.0
5,I-1006,Shenzhen,China,4/25/2016,Iron,30.0
6,I-1007,Lima,Peru,6/6/2016,Dishwasher,500.0
7,I-1008,Tijuana,Mexico,6/7/2016,Iron,30.0
8,I-1009,London,UK,12/11/2015,Washing Machine,800.0
9,I-1010,Lima,Peru,9/7/2014,Iron,30.0
10,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000.0
11,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700.0
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30.0
13,I-1014,Delhi,India,5/30/2014,Oven,500.0
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800.0
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80.0
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000.0