In [19]:
import pandas as pd

df1=pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})
df2=pd.DataFrame({"C":[10,20,30,40],"D":[12,12,13,14]})

df1.join(df2)

   A   B   C   D
0  1  11  10  12
1  2  22  20  12
2  3  33  30  13
3  4  44  40  14

In [20]:
df1=pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})
df2=pd.DataFrame({"C":[10,20],"D":[12,12]})

df1.join(df2)

   A   B     C     D
0  1  11  10.0  12.0
1  2  22  20.0  12.0
2  3  33   NaN   NaN
3  4  44   NaN   NaN

In [21]:
df1=pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]},index=["a","b","c","d"])
df2=pd.DataFrame({"C":[10,20],"D":[12,12]},index=["a","b"])

# df1.join(df2)
df2.join(df1)
# df2.join(df1,how="left")
# df2.join(df1,how="right")
# df2.join(df1,how="outer")
df2.join(df1,how="inner")

    C   D  A   B
a  10  12  1  11
b  20  12  2  22

In [22]:
df1=pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]},index=["a","b","c","d"])
df2=pd.DataFrame({"A":[10,20],"B":[12,12]},index=["a","b"])

# df1.join(df2,how="inner",lsuffix="_1")
df1.join(df2,how="inner",lsuffix="_1",rsuffix="_2")

   A_1  B_1  A_2  B_2
a    1   11   10   12
b    2   22   20   12

In [24]:
df1=pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]},index=["a","b","c","d"])
df2=pd.DataFrame({"A":[10,20],"B":[12,12]},index=["a","b"])

df1.add(df2)

      A     B
a  11.0  23.0
b  22.0  34.0
c   NaN   NaN
d   NaN   NaN

In [26]:
dfnew1=pd.DataFrame({"Days":[1,2,3,4],"English":[11,22,33,44],"Maths":[34,45,78,63]})
dfnew1

   Days  English  Maths
0     1       11     34
1     2       22     45
2     3       33     78
3     4       44     63

In [33]:
# pd.melt(dfnew1)
# pd.melt(dfnew1,id_vars=["Maths"])
# pd.melt(dfnew1,id_vars=["Days"])
# pd.melt(dfnew1,id_vars=["Days"],var_name="Subjects")
pd.melt(dfnew1,id_vars=["Days"],var_name="Subjects",value_name="TotalMarks")

   Days Subjects  TotalMarks
0     1  English          11
1     2  English          22
2     3  English          33
3     4  English          44
4     1    Maths          34
5     2    Maths          45
6     3    Maths          78
7     4    Maths          63

In [38]:
import pandas as pd
dfnew1=pd.DataFrame({"Days":[1,2,3,4],"StdName":["Rohan","Shyam","Ravi","Mohan"],"English":[11,22,33,44],"Maths":[34,45,78,63]})
dfnew1
# dfnew1.pivot(index="Days",columns="StdName")
dfnew1.pivot(index="Days",columns="StdName",values="English")

StdName  Mohan  Ravi  Rohan  Shyam
Days
1          NaN   NaN   11.0    NaN
2          NaN   NaN    NaN   22.0
3          NaN  33.0    NaN    NaN
4         44.0   NaN    NaN    NaN

In [46]:
import pandas as pd
dfnew1=pd.DataFrame({"Days":[1,1,1,2],"StdName":["Rohan","Shyam","Ravi","Mohan"],"English":[11,22,33,44],"Maths":[34,45,78,63]})
# dfnew1
# dfnew1.pivot_table(index="StdName",columns="Days",aggfunc="mean")
# dfnew1.pivot_table(index="StdName",columns="Days",aggfunc="median")
dfnew1.pivot_table(index="StdName",columns="Days",aggfunc="sum",margins=True)

        English             Maths
Days          1     2  All      1     2  All
StdName
Mohan       NaN  44.0   44    NaN  63.0   63
Ravi       33.0   NaN   33   78.0   NaN   78
Rohan      11.0   NaN   11   34.0   NaN   34
Shyam      22.0   NaN   22   45.0   NaN   45
All        66.0  44.0  110  157.0  63.0  220