### Merge DataFames

In [1]:
import pandas as pd

var1=pd.DataFrame({"A":[1,2,3,4],"B":[2,4,7,1]})

var2=pd.DataFrame({"A":[1,2,3,5],"C":[12,14,17,11]})

# print(var1)
# print(var2)

# pd.merge(var1,var2)

# pd.merge(var1,var2,on="A")

# pd.merge(var1,var2,how="inner")

# A B C

In [2]:
var1=pd.DataFrame({"A":[1,2,3,6],"B":[2,4,7,1]})
var2=pd.DataFrame({"A":[1,2,3,5],"C":[12,14,17,11]})

# pd.merge(var1,var2,how="left")

# pd.merge(var1,var2,how="right")
pd.merge(var2,var1,how="outer")

   A     C    B
0  1  12.0  2.0
1  2  14.0  4.0
2  3  17.0  7.0
3  5  11.0  NaN
4  6   NaN  1.0

In [3]:
var1=pd.DataFrame({"A":[1,2,3,6],"B":[2,4,7,1]})
var2=pd.DataFrame({"A":[1,2,3,5],"B":[12,14,17,11]})

pd.merge(var1,var2,left_index=True,right_index=True)
# pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("python","java"))
pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("-1","-2"))

# print("Hello"+"Hifzur")

   A-1  B-1  A-2  B-2
0    1    2    1   12
1    2    4    2   14
2    3    7    3   17
3    6    1    5   11

In [4]:
sr1=pd.Series([1,2,3,4,6])
sr2=pd.Series([11,12,13,14])

# pd.concat([sr1,sr2])
# pd.concat([sr1,sr2],axis=0)
# pd.concat([sr1,sr2],axis=1)

In [5]:
df1=pd.DataFrame({"A":[1,2,3,6],"B":[2,4,7,1]})
df2=pd.DataFrame({"A1":[1,2,3,5],"B1":[12,14,17,11]})

# pd.concat([df1,df2],axis=0)
# pd.concat([df1,df2],axis=1)

In [6]:
df1=pd.DataFrame({"A":[1,2,3,6],"B":[2,4,7,1]})
df2=pd.DataFrame({"A":[1,2,5],"B":[12,14,78]})

# pd.concat([df1,df2],axis=0,join="inner")
# pd.concat([df1,df2],axis=1,join="outer")
pd.concat([df1,df2],axis=1,join="outer",keys=["data1","data2"])

  data1    data2
      A  B     A     B
0     1  2   1.0  12.0
1     2  4   2.0  14.0
2     3  7   5.0  78.0
3     6  1   NaN   NaN

In [7]:
df1=pd.DataFrame({"A":[1,2,3,6]})
df2=pd.DataFrame({"A":[1,2],"B":[12,14]})

pd.concat([df1,df2],axis=0)
# pd.concat([df1,df2],axis=1)

   A     B
0  1   NaN
1  2   NaN
2  3   NaN
3  6   NaN
0  1  12.0
1  2  14.0

In [8]:
df1=pd.DataFrame({"D":[1,2,3,6]})
df2=pd.DataFrame({"A":[1,2],"B":[12,14]})

pd.concat([df1,df2])

     D    A     B
0  1.0  NaN   NaN
1  2.0  NaN   NaN
2  3.0  NaN   NaN
3  6.0  NaN   NaN
0  NaN  1.0  12.0
1  NaN  2.0  14.0

In [9]:
import pandas as pd

newdf1=pd.DataFrame({
    "Product":["Computer","Ram","Ram","Computer","Ram","Ram","Rom","Computer","Rom","Rom","Rom","Ram"],
    "2021":[12,34,56,56,45,54,34,87,96,55,33,98],
    "2022":[56,45,54,34,87,12,96,55,33,98,34,56]
})

newdf1

     Product  2021  2022
0   Computer    12    56
1        Ram    34    45
2        Ram    56    54
3   Computer    56    34
4        Ram    45    87
5        Ram    54    12
6        Rom    34    96
7   Computer    87    55
8        Rom    96    33
9        Rom    55    98
10       Rom    33    34
11       Ram    98    56

In [10]:
varGp=newdf1.groupby("Product")

varGp

In [11]:
for key,value in varGp:
    print(key)
    print(value)
    print("----------------------------")

Computer
    Product  2021  2022
0  Computer    12    56
3  Computer    56    34
7  Computer    87    55
----------------------------
Ram
   Product  2021  2022
1      Ram    34    45
2      Ram    56    54
4      Ram    45    87
5      Ram    54    12
11     Ram    98    56
----------------------------
Rom
   Product  2021  2022
6      Rom    34    96
8      Rom    96    33
9      Rom    55    98
10     Rom    33    34
----------------------------

In [12]:
varGp.get_group("Computer")

    Product  2021  2022
0  Computer    12    56
3  Computer    56    34
7  Computer    87    55

In [13]:
varGp.min()

          2021  2022
Product
Computer    12    34
Ram         34    12
Rom         33    33

In [14]:
varGp.max()

          2021  2022
Product
Computer    87    56
Ram         98    87
Rom         96    98

In [15]:
varGp.mean()

               2021       2022
Product
Computer  51.666667  48.333333
Ram       57.400000  50.800000
Rom       54.500000  65.250000

In [16]:
varGp.median()

          2021  2022
Product
Computer  56.0  55.0
Ram       54.0  54.0
Rom       44.5  65.0

In [17]:
list1=list(varGp)
list1

[('Computer',
      Product  2021  2022
  0  Computer    12    56
  3  Computer    56    34
  7  Computer    87    55),
 ('Ram',
     Product  2021  2022
  1      Ram    34    45
  2      Ram    56    54
  4      Ram    45    87
  5      Ram    54    12
  11     Ram    98    56),
 ('Rom',
     Product  2021  2022
  6      Rom    34    96
  8      Rom    96    33
  9      Rom    55    98
  10     Rom    33    34)]