# Read CSV Data

In [62]:
import pandas as pd
# read1=pd.read_csv("./myfile2.csv")
read1=pd.read_csv("./csv1.csv")
# print(read1)
read1

,JE Code,Store,Country,Date,Item,List Price
0,I-1001,Moscow,Russia,10/6/2018,Microwave,80
1,I-1002,Toronto,Canada,4/23/2015,Microwave,80
2,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
3,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
4,I-1005,Sydney,Australia,3/3/2015,Toaster,50
5,I-1006,Shenzhen,China,4/25/2016,Iron,30
6,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
7,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
8,I-1009,London,UK,12/11/2015,Washing Machine,800
9,I-1010,Lima,Peru,9/7/2014,Iron,30
10,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
11,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
13,I-1014,Delhi,India,5/30/2014,Oven,500
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [63]:
read1.index

RangeIndex(start=0, stop=17, step=1)

In [64]:
read1.columns

Index(['JE Code', 'Store', 'Country', 'Date', 'Item', 'List Price'], dtype='str')

In [65]:
read1.describe()

# 2,5,6,8

# 2+4+5+8/4=5.5

2,5,5.5,6,8

(2, 5, 5.5, 6, 8)

In [66]:
read1.head()

  JE Code      Store    Country       Date             Item  List Price
0  I-1001     Moscow     Russia  10/6/2018        Microwave          80
1  I-1002    Toronto     Canada  4/23/2015        Microwave          80
2  I-1003  Sao Paolo     Brazil   4/3/2017  Air conditioner         700
3  I-1004   Istanbul     Turkey  8/14/2018      Ceiling fan         150
4  I-1005     Sydney  Australia   3/3/2015          Toaster          50

In [67]:
read1.head(2)

  JE Code    Store Country       Date       Item  List Price
0  I-1001   Moscow  Russia  10/6/2018  Microwave          80
1  I-1002  Toronto  Canada  4/23/2015  Microwave          80

In [68]:
read1.tail(2)

   JE Code             Store  Country       Date          Item  List Price
15  I-1016  Ho Chi Minh City  Vietnam  5/24/2015     Microwave          80
16  I-1017          Tel Aviv   Israel  12/6/2014  Refrigerator        1000

In [69]:
read1.tail()

,JE Code,Store,Country,Date,Item,List Price
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
13,I-1014,Delhi,India,5/30/2014,Oven,500
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [70]:
read1[5:11]

   JE Code     Store       Country        Date             Item  List Price
5   I-1006  Shenzhen         China   4/25/2016             Iron          30
6   I-1007      Lima          Peru    6/6/2016       Dishwasher         500
7   I-1008   Tijuana        Mexico    6/7/2016             Iron          30
8   I-1009    London            UK  12/11/2015  Washing Machine         800
9   I-1010      Lima          Peru    9/7/2014             Iron          30
10  I-1011    Riyadh  Saudi Arabia   10/7/2017     Refrigerator        1000

In [71]:
read1.index.array

<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Length: 17, dtype: int64

In [72]:
read1.to_numpy()

array([['I-1001', 'Moscow', 'Russia', '10/6/2018', 'Microwave', 80],
       ['I-1002', 'Toronto', 'Canada', '4/23/2015', 'Microwave', 80],
       ['I-1003', 'Sao Paolo', 'Brazil', '4/3/2017', 'Air conditioner',
        700],
       ['I-1004', 'Istanbul', 'Turkey', '8/14/2018', 'Ceiling fan', 150],
       ['I-1005', 'Sydney', 'Australia', '3/3/2015', 'Toaster', 50],
       ['I-1006', 'Shenzhen', 'China', '4/25/2016', 'Iron', 30],
       ['I-1007', 'Lima', 'Peru', '6/6/2016', 'Dishwasher', 500],
       ['I-1008', 'Tijuana', 'Mexico', '6/7/2016', 'Iron', 30],
       ['I-1009', 'London', 'UK', '12/11/2015', 'Washing Machine', 800],
       ['I-1010', 'Lima', 'Peru', '9/7/2014', 'Iron', 30],
       ['I-1011', 'Riyadh', 'Saudi Arabia', '10/7/2017', 'Refrigerator',
        1000],
       ['I-1012', 'Bangkok', 'Thailand', '8/21/2014', 'Air conditioner',
        700],
       ['I-1013', 'Tijuana', 'Mexico', '3/9/2015', 'Iron', 30],
       ['I-1014', 'Delhi', 'India', '5/30/2014', 'Oven', 500],
       ['I-1015', 'Sydney', 'Australia', '11/12/2018', 'Washing Machine',
        800],
       ['I-1016', 'Ho Chi Minh City', 'Vietnam', '5/24/2015',
        'Microwave', 80],
       ['I-1017', 'Tel Aviv', 'Israel', '12/6/2014', 'Refrigerator',
        1000]], dtype=object)

In [73]:
import numpy as np
v=np.asarray(read1)
v

array([['I-1001', 'Moscow', 'Russia', '10/6/2018', 'Microwave', 80],
       ['I-1002', 'Toronto', 'Canada', '4/23/2015', 'Microwave', 80],
       ['I-1003', 'Sao Paolo', 'Brazil', '4/3/2017', 'Air conditioner',
        700],
       ['I-1004', 'Istanbul', 'Turkey', '8/14/2018', 'Ceiling fan', 150],
       ['I-1005', 'Sydney', 'Australia', '3/3/2015', 'Toaster', 50],
       ['I-1006', 'Shenzhen', 'China', '4/25/2016', 'Iron', 30],
       ['I-1007', 'Lima', 'Peru', '6/6/2016', 'Dishwasher', 500],
       ['I-1008', 'Tijuana', 'Mexico', '6/7/2016', 'Iron', 30],
       ['I-1009', 'London', 'UK', '12/11/2015', 'Washing Machine', 800],
       ['I-1010', 'Lima', 'Peru', '9/7/2014', 'Iron', 30],
       ['I-1011', 'Riyadh', 'Saudi Arabia', '10/7/2017', 'Refrigerator',
        1000],
       ['I-1012', 'Bangkok', 'Thailand', '8/21/2014', 'Air conditioner',
        700],
       ['I-1013', 'Tijuana', 'Mexico', '3/9/2015', 'Iron', 30],
       ['I-1014', 'Delhi', 'India', '5/30/2014', 'Oven', 500],
       ['I-1015', 'Sydney', 'Australia', '11/12/2018', 'Washing Machine',
        800],
       ['I-1016', 'Ho Chi Minh City', 'Vietnam', '5/24/2015',
        'Microwave', 80],
       ['I-1017', 'Tel Aviv', 'Israel', '12/6/2014', 'Refrigerator',
        1000]], dtype=object)

In [81]:
read1.sort_index(axis=0)
# read1.sort_index(axis=0,ascending=False)

,JE Code,Store,Country,Date,Item,List Price
0,I-1001,Moscow,Russia,10/6/2018,Microwave,80
1,I-1002,Rohan,Canada,4/23/2015,Microwave,80
2,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
3,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
4,I-1005,Sydney,Australia,3/3/2015,Toaster,50
5,I-1006,Shenzhen,China,4/25/2016,Iron,30
6,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
7,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
8,I-1009,London,UK,12/11/2015,Washing Machine,800
9,I-1010,Lima,Peru,9/7/2014,Iron,30
10,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
11,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
13,I-1014,Delhi,India,5/30/2014,Oven,500
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [83]:
read1.loc[1,"Store"]="Sajid"
read1

,JE Code,Store,Country,Date,Item,List Price
0,I-1001,Moscow,Russia,10/6/2018,Microwave,80
1,I-1002,Sajid,Canada,4/23/2015,Microwave,80
2,I-1003,Sao Paolo,Brazil,4/3/2017,Air conditioner,700
3,I-1004,Istanbul,Turkey,8/14/2018,Ceiling fan,150
4,I-1005,Sydney,Australia,3/3/2015,Toaster,50
5,I-1006,Shenzhen,China,4/25/2016,Iron,30
6,I-1007,Lima,Peru,6/6/2016,Dishwasher,500
7,I-1008,Tijuana,Mexico,6/7/2016,Iron,30
8,I-1009,London,UK,12/11/2015,Washing Machine,800
9,I-1010,Lima,Peru,9/7/2014,Iron,30
10,I-1011,Riyadh,Saudi Arabia,10/7/2017,Refrigerator,1000
11,I-1012,Bangkok,Thailand,8/21/2014,Air conditioner,700
12,I-1013,Tijuana,Mexico,3/9/2015,Iron,30
13,I-1014,Delhi,India,5/30/2014,Oven,500
14,I-1015,Sydney,Australia,11/12/2018,Washing Machine,800
15,I-1016,Ho Chi Minh City,Vietnam,5/24/2015,Microwave,80
16,I-1017,Tel Aviv,Israel,12/6/2014,Refrigerator,1000

In [85]:
read1.loc[[2,3],["Store","Country","Date"]]

       Store Country       Date
2  Sao Paolo  Brazil   4/3/2017
3   Istanbul  Turkey  8/14/2018

In [89]:
# read1.loc[[2,3],:]
read1.loc[5:8,:]

  JE Code     Store Country        Date             Item  List Price
5  I-1006  Shenzhen   China   4/25/2016             Iron          30
6  I-1007      Lima    Peru    6/6/2016       Dishwasher         500
7  I-1008   Tijuana  Mexico    6/7/2016             Iron          30
8  I-1009    London      UK  12/11/2015  Washing Machine         800

In [91]:
read1.iloc[5,2]

'China'

In [92]:
read1.drop("Store",axis=1)

   JE Code       Country        Date             Item  List Price
0   I-1001        Russia   10/6/2018        Microwave          80
1   I-1002        Canada   4/23/2015        Microwave          80
2   I-1003        Brazil    4/3/2017  Air conditioner         700
3   I-1004        Turkey   8/14/2018      Ceiling fan         150
4   I-1005     Australia    3/3/2015          Toaster          50
5   I-1006         China   4/25/2016             Iron          30
6   I-1007          Peru    6/6/2016       Dishwasher         500
7   I-1008        Mexico    6/7/2016             Iron          30
8   I-1009            UK  12/11/2015  Washing Machine         800
9   I-1010          Peru    9/7/2014             Iron          30
10  I-1011  Saudi Arabia   10/7/2017     Refrigerator        1000
11  I-1012      Thailand   8/21/2014  Air conditioner         700
12  I-1013        Mexico    3/9/2015             Iron          30
13  I-1014         India   5/30/2014             Oven         500
14  I-1015     Australia  11/12/2018  Washing Machine         800
15  I-1016       Vietnam   5/24/2015        Microwave          80
16  I-1017        Israel   12/6/2014     Refrigerator        1000