# Pandas Series Lecture 1

In [1]:
import pandas as pd # alia name

data1=pd.Series([5,3,2,8])

print(data1)
print(type(data1))

0    5
1    3
2    2
3    8
dtype: int64
<class 'pandas.Series'>

In [2]:
data2=pd.Series([5,3,2,8],index=["A1","B1","C","D"],dtype=float,name="Python Data")
print(data2)

A1    5.0
B1    3.0
C     2.0
D     8.0
Name: Python Data, dtype: float64

In [3]:
dic={"sub":["phy","chem","math"],"marks":[20,45,89],"rank":[2,5,7]}
ser1=pd.Series(dic)
print(ser1)

sub      [phy, chem, math]
marks         [20, 45, 89]
rank             [2, 5, 7]
dtype: object

In [4]:
dic1={11:[34,23,23],12:[20,45,89],31:[2,5,7]}
ser2=pd.Series(dic1)
print(ser2)

11    [34, 23, 23]
12    [20, 45, 89]
31       [2, 5, 7]
dtype: object

In [5]:
s1=pd.Series(34,index=[1,2,3,4,5])

print(s1)

print(type(s1))

1    34
2    34
3    34
4    34
5    34
dtype: int64
<class 'pandas.Series'>

In [6]:
d1=pd.Series(12,index=[1,5,7,8])

d2=pd.Series(15,index=[1,3,6,8])
print(d1)
print(d2)

print(d1+d2)

1    12
5    12
7    12
8    12
dtype: int64
1    15
3    15
6    15
8    15
dtype: int64
1    27.0
3     NaN
5     NaN
6     NaN
7     NaN
8    27.0
dtype: float64

In [7]:
s1=pd.Series(12,index=[1,2,5,7,8,9])
s2=pd.Series(12,index=[1,3,5,7])
print(s1+s2)

1    24.0
2     NaN
3     NaN
5    24.0
7    24.0
8     NaN
9     NaN
dtype: float64

# Data Frame

In [8]:
l1={"a":[1,2,4,6],"b":[4,6,8,9],"c":[2,3,5,6]}

data1=pd.DataFrame(l1)

# print(data1)
# print(type(data1))
data1

   a  b  c
0  1  4  2
1  2  6  3
2  4  8  5
3  6  9  6

In [9]:
l2={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}

data2=pd.DataFrame(l2,columns=["a","d","s"],index=["a1","s1","d1","f1"])
# data2=pd.DataFrame(l2,columns=["a","d"],index=[1,3,4,5])
print(data2)
print(type(data2))

    a  d  s
a1  1  2  4
s1  2  3  6
d1  4  5  8
f1  6  6  9
<class 'pandas.DataFrame'>

In [10]:
list1=[[2,3,4,7],[3,5,6,4],[2,8,6,4]]

d2=pd.DataFrame(list1)

print(d2)

   0  1  2  3
0  2  3  4  7
1  3  5  6  4
2  2  8  6  4

In [11]:
s1={"a":pd.Series([4,2,9,6]),"b":pd.Series([2,9,5,3],)}

data2=pd.DataFrame(s1)

# print(data2)

# print(data2["a"][2])
print(data2["b"][2])

5

# Arithmetic operation in DataFrame

In [12]:
d4=pd.DataFrame({"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]})

# d4["sum"]=d4["a"]+d4["d"]+d4["s"]
# d4

In [13]:
d4["Multi"]=d4["s"]*d4["d"]

d4["D4>20"]=d4["Multi"]>20
d4

   a  s  d  Multi  D4>20
0  1  4  2      8  False
1  2  6  3     18  False
2  4  8  5     40   True
3  6  9  6     54   True

In [14]:
d4["Sum"]=d4["a"]+d4["s"]+d4["d"]
d4
d4["Diff(a-b)"]=d4["a"]-d4["s"]
d4
d4["Mul(a*b)"]=d4["a"]*d4["s"]
d4
d4["Div(a/b)"]=d4["a"]/d4["s"]
d4

   a  s  d  Multi  D4>20  Sum  Diff(a-b)  Mul(a*b)  Div(a/b)
0  1  4  2      8  False    7         -3         4  0.250000
1  2  6  3     18  False   11         -4        12  0.333333
2  4  8  5     40   True   17         -4        32  0.500000
3  6  9  6     54   True   21         -3        54  0.666667

In [15]:
# d4[">20"]=d4["Sum"]>=20
# d4

# Insert and Delete Data

In [16]:
l1={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}

data1=pd.DataFrame(l1)

data1.insert(2,"Data1",data1["s"]*5)

# data1.insert(1,"Data1",data1["s"])
print(data1)

   a  s  Data1  d
0  1  4     20  2
1  2  6     30  3
2  4  8     40  5
3  6  9     45  6

In [17]:
l1={"a":[1,2,4,6],"s":[4,6,8,9],"d":[2,3,5,6]}
data1=pd.DataFrame(l1)
data1.insert(1,"Data1",[4,6,7,8])
print(data1)

   a  Data1  s  d
0  1      4  4  2
1  2      6  6  3
2  4      7  8  5
3  6      8  9  6

In [18]:
data1["new"]=data1["s"][1:]
data1
data1.pop("a")
data1

   Data1  s  d  new
0      4  4  2  NaN
1      6  6  3  6.0
2      7  8  5  8.0
3      8  9  6  9.0

In [19]:
# data1["new"]=data1["s"][:2]
# data1

In [20]:
data1.pop("s")
data1

   Data1  d  new
0      4  2  NaN
1      6  3  6.0
2      7  5  8.0
3      8  6  9.0

In [21]:
del data1["d"]
data1

   Data1  new
0      4  NaN
1      6  6.0
2      7  8.0
3      8  9.0