In [18]:
import pandas as pd

data1=pd.read_csv("newtest.csv")

data1

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179   2nd           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447   2nd             Jaunpur
3      4         Nikhil Rai   9305080327   2nd  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124   2nd          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056   2nd            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344   2nd              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026   2nd      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619   2nd            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204   2nd     Khitaura Badaun
15    16       Aditya Kumar   7645071129   2nd          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377   2nd             Jaunpur
18    19        Laki Sharma   8267968235   2nd         TiliyaKhata
19    20     Utkarsh Sharma   7317762256   2nd         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992   2nd                 Mau
23    24            Shivraj   8409108148   2nd                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943   2nd              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010   2nd            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [19]:
# data1.replace(to_replace="2nd",value="4rth")
data1.replace("2nd","4rth")

    S.N.               Name  Contact No.  Year             Address
0      1     Mohit Tripathi   8887331179  4rth           Prayagraj
1      2        Jay Narayan   9511493970   3rd           Sultanpur
2      3           Aman Pal   9151503447  4rth             Jaunpur
3      4         Nikhil Rai   9305080327  4rth  Maunath Bhajan Mau
4      5       Sonush Kumar   8400716124  4rth          Shajahapur
5      6        Vivek Kumar   9151480914   3rd           Sonbhadra
6      7      Pranshu Dubey   8707037056  4rth            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8      9       Sujeet Kumar   9565256344  4rth              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026  4rth      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619  4rth            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204  4rth     Khitaura Badaun
15    16       Aditya Kumar   7645071129  4rth          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377  4rth             Jaunpur
18    19        Laki Sharma   8267968235  4rth         TiliyaKhata
19    20     Utkarsh Sharma   7317762256  4rth         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21    22       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992  4rth                 Mau
23    24            Shivraj   8409108148  4rth                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943  4rth              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010  4rth            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [20]:
data1.replace([1,2,3,4,5,6,7,9,22],455)
# data1.replace("2nd",5)

    S.N.               Name  Contact No.  Year             Address
0    455     Mohit Tripathi   8887331179   2nd           Prayagraj
1    455        Jay Narayan   9511493970   3rd           Sultanpur
2    455           Aman Pal   9151503447   2nd             Jaunpur
3    455         Nikhil Rai   9305080327   2nd  Maunath Bhajan Mau
4    455       Sonush Kumar   8400716124   2nd          Shajahapur
5    455        Vivek Kumar   9151480914   3rd           Sonbhadra
6    455      Pranshu Dubey   8707037056   2nd            Mirzapur
7      8       Vishal Kumar   8273730104   3rd            Bareilly
8    455       Sujeet Kumar   9565256344   2nd              Ballia
9     10        Niraj Kumar   7310362981   NaN              Ballia
10    11        Mohit Yadav   9721334026   2nd      Ambedkar Nagar
11    12   Himanshu Katiyar   9897515619   2nd            Bareilly
12    13       Mayank Singh   8960959096   NaN         RaeBareilly
13    14       Shivam Kumar   8102375878   3rd               Patna
14    15  Kishan Raghuvansh   7451099204   2nd     Khitaura Badaun
15    16       Aditya Kumar   7645071129   2nd          Gaya Bihar
16    17         Farman Ali   9027969463  4rth            Bareilly
17    18              Arpit   8853029377   2nd             Jaunpur
18    19        Laki Sharma   8267968235   2nd         TiliyaKhata
19    20     Utkarsh Sharma   7317762256   2nd         Shajahanpur
20    21              Akash   7398558431   NaN                 Mau
21   455       Vikash Yadav   8115514548  4rth              Ballia
22    23         Ashu Yadav   8115191992   2nd                 Mau
23    24            Shivraj   8409108148   2nd                 Mau
24    25      Karan Bhrdwaj   9795590870  4rth          Farukhabad
25    26        Anuj Gautam   8601097943   2nd              Kanpur
26    27        Ankit Kumar   7817895076  4rth            Bareilly
27    28        Arjun Singh   9389454010   2nd            Bareilly
28    29   Prince Prajapati   7800170358   3rd           Gorakhpur

In [21]:
# data1.replace("[A-Ha-h]","Python",regex=True)
# data1.replace("[A-F]","panda",regex=True)
# data1.replace("[A-Fa-z]","panda",regex=True)

# data1.replace("[0-9]","panda",regex=True)

In [26]:
data1.replace({"Year":"2nd"},56,regex=True)
data1

,S.N.,Name,Contact No.,Year,Address,Price Winner
0,1.0,Mohit Tripathi,8.887331e+09,56,Prayagraj,NaN
1,2.0,Jay Narayan,9.511494e+09,3rd,Sultanpur,3000.0
2,3.0,Aman Pal,9.151503e+09,56,Jaunpur,4000.0
3,4.0,Nikhil Rai,9.305080e+09,56,Maunath Bhajan Mau,5000.0
4,5.0,Sonush Kumar,8.400716e+09,56,Shajahapur,6000.0
5,6.0,Vivek Kumar,9.151481e+09,3rd,Sonbhadra,7000.0
6,7.0,Pranshu Dubey,8.707037e+09,56,Mirzapur,NaN
7,8.0,NaN,8.273730e+09,3rd,Bareilly,NaN
8,9.0,NaN,9.565256e+09,56,Ballia,3000.0
9,10.0,NaN,7.310363e+09,NaN,Ballia,4000.0
10,11.0,NaN,NaN,56,Ambedkar Nagar,5000.0
11,12.0,NaN,NaN,56,Bareilly,NaN
12,13.0,NaN,NaN,NaN,RaeBareilly,NaN
13,14.0,Shivam Kumar,NaN,3rd,Patna,2000.0
14,15.0,Kishan Raghuvansh,NaN,56,Khitaura Badaun,3000.0
15,16.0,Aditya Kumar,7.645071e+09,56,Gaya Bihar,4000.0
16,17.0,Farman Ali,9.027969e+09,4rth,Bareilly,5000.0
17,18.0,Arpit,8.853029e+09,56,Jaunpur,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN
20,21.0,NaN,7.398558e+09,NaN,Mau,NaN
21,22.0,NaN,8.115515e+09,4rth,Ballia,NaN
22,23.0,NaN,8.115192e+09,56,Mau,2000.0
23,24.0,Shivraj,8.409108e+09,56,Mau,3000.0
24,25.0,Karan Bhrdwaj,9.795591e+09,4rth,Farukhabad,4000.0
25,26.0,Anuj Gautam,8.601098e+09,56,Kanpur,5000.0
26,27.0,Ankit Kumar,7.817895e+09,4rth,Bareilly,6000.0
27,28.0,Arjun Singh,9.389454e+09,56,Bareilly,7000.0
28,29.0,Prince Prajapati,7.800170e+09,3rd,Gorakhpur,8000.0